### ISSUE TITLE
Add a CLI switch to disable source maps

### ISSUE THREAD

**Issue by nstCactus** [directus/extension-toolkit#19]
Parcel has a [bug with existing sourcem maps](https://github.com/parcel-bundler/parcel/issues/2795), which can prevent the Directus extension toolkit to build extensions that depend on NPM packages having source maps.

I was able to temporarily work this around by editing the _node_modules/@directus/extension-toolkit/cli/cmds/build.js_ & _node_modules/@directus/extension-toolkit/cli/cmds/watch.js_ files in my extension directory. I had to append the `sourceMaps: false` property to the second parameter of the `Bundler` constructor.

It would be nice to add a CLI switch (say `--no-source-maps` to be consitent with Parcel), to disable source map generation.

**Comment by rijkvanzanten** [comment]
Do you wanna add a PR for that @nstCactus ?
