### ISSUE TITLE
Interface looking for display.css 

### ISSUE THREAD

**Issue by philleepflorence** [directus/extension-toolkit#21]
### What
After building a custom interface, it seems **input.css** is created while the **Suite** looks for **display.css**.

### Error Generated
```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
```

**Comment by philleepflorence** [comment]
It seems a style tag with at least one definition is required to create the display.css.
The same goes for input.css.

**Comment by rijkvanzanten** [comment]
The app will always attempt to download the input.css and display.css files, as there is no way to know in advance if those files exist or not.

**Comment by philleepflorence** [comment]
I think the boilerplate should include a blank style tag with the root element or a comment line to alert the user to include a style, as Vue does not require a style tag but the extension does, so that may be confusing.
Or the extension maker generates a blank input or display CSS file where applicable.
Or the README or DOCs updated to alert the user.

**Comment by rijkvanzanten** [comment]
The boilerplate does include a style tag, or are you referring to a place somewhere else?

https://github.com/directus/extension-toolkit/blob/82c867e52230a62df3c8d7465e35ad26b8f6df67/cli/templates/display.vue#L21-L25
