### ISSUE TITLE
ReferenceError: sourceMaps is not defined

### ISSUE THREAD

**Issue by mironcat** [directus/extension-toolkit#22]
After update to version 0.0.7 I have error "ReferenceError: sourceMaps is not defined"
my command is:
`
directus-extensions watch  --input ./src --output ./dist
`

**Comment by rijkvanzanten** [comment]
This seems to be introduced in https://github.com/directus/extension-toolkit/pull/20. @nstCactus any thoughts?

**Comment by rijkvanzanten** [comment]
Damn you on top of things @nstCactus , thanks! 👏
