### ISSUE TITLE
Custom output folder not working anymore

### ISSUE THREAD

**Issue by Kinzi** [directus/extension-toolkit#24]
I used to npm run build / npm run dev right into directus like this:

`npm run build --input ./src --output /Users/directus/public/extensions/custom/interfaces/name`

Since I updated the toolkit I get the following error:

```
No entries found.
    at Bundler.bundle (/usr/local/lib/node_modules/@directus/extension-toolkit/node_modules/parcel-bundler/src/Bundler.js:275:17)
    at <anonymous>
```

normal `npm run dev / build`without folder specifications works.

**Comment by rijkvanzanten** [comment]
Is the path to `./src` correct? 

It's combining the path with `*.vue` over here:

https://github.com/directus/extension-toolkit/blob/9adeb47d57314274da7003f3e45c1b126b369588/cli/cmds/build.js#L20-L34

Does it work when omitting the `./` part in `./src`?

**Comment by Kinzi** [comment]
@rijkvanzanten 

I tried it without `./`and also with the absolute path for input. Same results:

```
npm run dev --input /path/to/extension/src --output /path/to/directus/public/extensions/custom/interfaces/extension                                                                                                        

extension@1.0.1 dev /path/to/extension
directus-extensions watch "/path/to/extension/src" "/path/to/directus/public/extensions/custom/interfaces/product-ean"

🚨  No entries found.
    at Bundler.bundle (/usr/local/lib/node_modules/@directus/extension-toolkit/node_modules/parcel-bundler/src/Bundler.js:275:17)
    at <anonymous>
```

**Comment by rijkvanzanten** [comment]
Interestingly enough, it does work when running the `watch` script "manually" by using

`npx directus-extensions watch --input src` instead of `npm run dev --input src`

**Comment by rijkvanzanten** [comment]
Ahhh it's because you have to pass the arguments differently when using NPM:

https://stackoverflow.com/a/14404223/4859211

Try using `npm run dev -- --input /path/to/extension/src` instead 🙂

**Comment by rijkvanzanten** [comment]
I've updated the readme to reflect this

**Comment by Kinzi** [comment]
Yes - that's done the trick. Maybe without `--` still worked with an older NPM or something....

**Comment by rijkvanzanten** [comment]
Yeah.. must be! I'd swear it worked before 🤷‍♂

**Comment by Kinzi** [comment]
I definitely did for me ;)
