### ISSUE TITLE
Add an example of route

### ISSUE THREAD

**Issue by Silbad** [directus/extension-toolkit#31]
Hello,
Can you add an example with serval pages in one custom module ?
I can't get a page to work with the vue-router system...
Thanks

**Comment by rijkvanzanten** [comment]
Custom modules in v8 don't have sub routes. The custom module is a single page.

In v9, modules will be able to register multiple routes

**Comment by Silbad** [comment]
ok I understand, merci !

**Comment by rijkvanzanten** [comment]
We're hoping to have a first RC by the end of the week, so very soon 🙂
