### ISSUE TITLE
Incorrect route to js.map files in compiled output of custom extension

### ISSUE THREAD

**Issue by yarick2000** [directus/extension-toolkit#7]
Hi guys, 
It seems like in the compiled javascript file of custom extension (at least layout), the reference to the map file is incorrectly generated. Its pointing to the root folder:
//# sourceMappingURL=/layout.js.map
Instead, it should be referencing map file without specifying path at all , like that:
//# sourceMappingURL=layout.js.map
In this case browser will be able to load it and show the vue.js source in the developer panel.

**Comment by rijkvanzanten** [comment]
Closed in #12
